a=input('enter the username: ')
b=int(input('enter the age: '))
c=int(input('enter the password: '))
d=input('enter the designation: ')
e=input('enter the degree: ')
h=int(input('enter the degree percentage: '))
g=int(input('enter the salary: '))

f=open("emp.txt","a")
f.write("\n")
f.write(a)
f.write("\t")
f.write(str(b))
f.write("\t")
f.write(str(c))
f.write("\t")
f.write(d)
f.write("\t")
f.write(e)
f.write("\t")
f.write(str(h))
f.write("\t")
f.write(str(g))
f.write("\t")